"""empty message

Revision ID: 87d6c4ba4e59
Revises: 
Create Date: 2019-03-24 03:49:30.722354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d6c4ba4e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('usertype', sa.String(length=64), nullable=False),
    sa.Column('nricHash', sa.String(length=128), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionTitle', sa.Text(), nullable=False),
    sa.Column('questionOption', sa.Text(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('questionType', sa.String(length=64), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_dateTime'), 'question', ['dateTime'], unique=False)
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('question', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_dateTime'), 'response', ['dateTime'], unique=False)
    op.create_index(op.f('ix_response_response'), 'response', ['response'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_response'), table_name='response')
    op.drop_index(op.f('ix_response_dateTime'), table_name='response')
    op.drop_table('response')
    op.drop_index(op.f('ix_question_dateTime'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
